### PR TITLE
Set filename to support auto update feature 

### PR DESCRIPTION
**Pull request by cnkk**
The Tailscale client auto-update feature requires the sources list file in `/etc/apt/sources.list.d/tailscale.list` otherwise it won't work.

### CODE REVIEW

**Comment by artis3n** [comment]
@cnkk Can you link to Tailscale documentation or describe how you came to this realization? I can't see any reference to this in https://tailscale.com/kb/1067/update .

**Comment by cnkk** [comment]
Hi!

The auto update feature just triggers a `tailscale update` and it does not work.

```shell
exporter:~# tailscale update
This will update Tailscale from 1.60.1 to 1.62.0. Continue? [y/n] y
open /etc/apt/sources.list.d/tailscale.list: no such file or directory
```

And this when auto update is enabled:
```
Mar 14 21:50:29 exporter tailscaled[37719]: c2n: POST /update received
Mar 14 21:50:29 exporter tailscaled[37719]: c2n: running "systemd-run --wait --pipe --collect /usr/bin/tailscale update --yes"
Mar 14 21:50:29 exporter tailscaled[37719]: c2n: GET /update received
Mar 14 21:50:30 exporter tailscaled[37719]: c2n: update command failed: exit status 1, output: Running as unit: run-u958.service
Mar 14 21:50:30 exporter tailscaled[37719]: Updating Tailscale from 1.60.1 to 1.62.0; --yes given, continuing without prompts.
Mar 14 21:50:30 exporter tailscaled[37719]: open /etc/apt/sources.list.d/tailscale.list: no such file or directory
Mar 14 21:50:30 exporter tailscaled[37719]: Finished with result: exit-code
Mar 14 21:50:30 exporter tailscaled[37719]: Main processes terminated with: code=exited/status=1
Mar 14 21:50:30 exporter tailscaled[37719]: Service runtime: 338ms
```

I think this is the part in the source code: https://github.com/tailscale/tailscale/blob/08ebac9acb5d4a6d2ae6b01f282f1f0807c7561d/clientupdate/clientupdate.go#L428

**Comment by artis3n** [comment]
Thanks, that would do it! What is the sources list filename that you are seeing assigned instead of tailscale.list? We'll definitely merge this in but I want to better understand what's going on, see if we need to make changes to other distros, maybe file an issue up to Tailscale.

**Review by artis3n — APPROVED** [review]
Going to follow up this PR with a new Molecule test to run `tailscale update` and ensure we don't introduce a regression in the future.

**Pull request merged**
