### PR TITLE
Fixed tailscale status returning exit code 1 when not logged in

### PR DESCRIPTION
**Pull request by blmhemu**
Fixes https://github.com/artis3n/ansible-role-tailscale/issues/138

### CODE REVIEW

**Comment by artis3n** [comment]
Set a `TAILSCALE_CI_KEY` in your forked repo's secrets with a Tailscale ephemeral auth key (https://github.com/artis3n/ansible-role-tailscale#development-and-contributing) or let me know if you'd rather I create a branch off of your PR to have CI run on this, which would preserve your contribution.

**Comment by blmhemu** [comment]
Gimme a min. Let me check

**Comment by artis3n** [comment]
Also, if you can update this as well: https://github.com/artis3n/ansible-role-tailscale/blob/acf9e84c446ec62330ddedc09e6813ea3c5f4ea6/molecule/skip-authentication/verify.yml#L11

**Comment by blmhemu** [comment]
Done ! Pls check again.

**Comment by artis3n** [comment]
Not sure why these are failing, I assume the secret isn't set up correctly. But encountered a hiccup with Debian 11 so I'm working on https://github.com/artis3n/ansible-role-tailscale/issues/140 before validating and merging this.

**Comment by blmhemu** [comment]
Also, I observed something odd. If incase user puts a wrong auth key, then `tailscale up -authkey` takes a long time. Could you add a timeout ?

**Comment by artis3n** [comment]
> Also, I observed something odd. If incase user puts a wrong auth key, then `tailscale up -authkey` takes a long time before failing. Could you add a timeout ?

I'm relying on the native timeout in that command but you're right, the command ends very quickly if successful. I'll add a shorter timeout in the future - can you add an issue for this?

**Comment by artis3n** [comment]
Pull in the latest changes from the main branch and then we can get this CI passing.

**Comment by blmhemu** [comment]
Done ! Merged upstream

**Review by artis3n — APPROVED** [review]

**Comment by blmhemu** [comment]
Sure ! @artis3n

**Comment by artis3n** [comment]
Thanks! I should have done that validation at the start.

**Pull request closed without merging**
