### PR TITLE
Prefix vars to prevent conflict with other roles

### PR DESCRIPTION
**Pull request by hollow**

### CODE REVIEW

**Comment by artis3n** [comment]
Great callout with this PR - will definitely merge. Do you think the prefix be more specific to this role, e.g. `artis3n_tailscale_`?

**Comment by artis3n** [comment]
CI errors are due to https://github.com/artis3n/ansible-role-tailscale/issues/279 , will re-run in a bit.

**Comment by hollow** [comment]
I think just using `tailscale` as prefix is fine. The only conflict that I came across until now is in https://github.com/dev-sec/ansible-collection-hardening/blob/154f862ccd839ee72f771895d4ee0f956327a686/roles/os_hardening/tasks/yum.yml#L16

**Comment by artis3n** [comment]
Sounds good to me. While these vars shouldn't be modified by end users, renaming them technically breaks backwards compatibility so I'll hold off on merging until I'm ready to create the next major version bump.

Want to get https://github.com/artis3n/ansible-role-tailscale/issues/276 done in the next few days, then I'll merge both and we'll push out a new release.

**Pull request merged**
